service: wide-rides


provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}

package:

  exclude:
    - .git/**
    - .idea/**

functions:
  RequestUnicorn:
    handler: handler.handler
    role: WildRydesLambdaRole
    events:
      - http:
          path: ride
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: WildRydesApiGatewayAuthorizer
resources:
  Resources:
    WildRydesCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: WildRydes
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false

    WildRydesCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: WildRydesWebApp
        GenerateSecret: false
        UserPoolId:
          Ref: 'WildRydesCognitoUserPool'

    WildRydesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Rides
        AttributeDefinitions:
          - AttributeName: RideId
            AttributeType: S
        KeySchema:
          - AttributeName: RideId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    WildRydesLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: WildRydesLambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DynamoDBWriteAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource:
                    'Fn::GetAtt': [WildRydesDynamoDBTable, Arn]

##### code for part 2 of https://hands-on.cloud/serverless-framework-building-web-app-using-aws-lambda-amazon-api-gateway-s-3-dynamo-db-and-cognito-part-2
    # `ApiGatewayRestApi` is generated by sls, can be found in ./.serverless/...
    WildRydesApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: WildRydes
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [WildRydesCognitoUserPool, Arn]
        IdentitySource: method.request.header.Authorization


###### may not necessary? created by sls?
###### code below are for part-1 of https://hands-on.cloud/serverless-framework-building-web-app-using-aws-lambda-amazon-api-gateway-s-3-dynamo-db-and-cognito-part-2
#    WildRydesApiGatewayRestApi:
#      Type: AWS::ApiGateway::RestApi
#      Properties:
#        Name: WildRydes
#        EndpointConfiguration:
#          Types:
#            - EDGE
#
#    WildRydesApiGatewayAuthorizer:
#      Type: AWS::ApiGateway::Authorizer
#      Properties:
#        Name: WildRydes
#        RestApiId:
#          Ref: WildRydesApiGatewayRestApi
#        Type: COGNITO_USER_POOLS
#        ProviderARNs:
#          - Fn::GetAtt: [WildRydesCognitoUserPool, Arn]
#        IdentitySource: method.request.header.Authorization
#
#    WildRydeApiGatewayRidesResource:
#      Type: AWS::ApiGateway::Resource
#      Properties:
#        ParentId:
#          Fn::GetAtt: [WildRydesApiGatewayRestApi, RootResourceId]
#        PathPart: ride
#        RestApiId:
#          Ref: WildRydesApiGatewayRestApi
#
#   ##CORS https://stackoverflow.com/questions/40292888/enable-cors-for-api-gateway-in-cloudformation-template
#    WildRydesRideOptionsMethod:
#      Type: AWS::ApiGateway::Method
#      Properties:
#        AuthorizationType: NONE
#        RestApiId:
#          Ref: WildRydesApiGatewayRestApi
#        ResourceId:
#          Ref: WildRydeApiGatewayRidesResource
#        HttpMethod: OPTIONS
#        Integration:
#          IntegrationResponses:
#            - StatusCode: 200
#              ResponseParameters:
#                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
#                method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
#                method.response.header.Access-Control-Allow-Origin: "'*'"
#              ResponseTemplates:
#                application/json: ''
#          PassthroughBehavior: WHEN_NO_MATCH
#          RequestTemplates:
#            application/json: '{"statusCode": 200}'
#          Type: MOCK
#        MethodResponses:
#          - StatusCode: 200
#            ResponseModels:
#              application/json: 'Empty'
#            ResponseParameters:
#              method.response.header.Access-Control-Allow-Headers: false
#              method.response.header.Access-Control-Allow-Methods: false
#              method.response.header.Access-Control-Allow-Origin: false
#
#    WildRydesRidePostMethod:
#      Type: AWS::ApiGateway::Method
#      Properties:
#        AuthorizerId:
#          Ref: WildRydesApiGatewayAuthorizer
#        AuthorizationType: COGNITO_USER_POOLS
#        HttpMethod: POST
#        ResourceId:
#          Ref: WildRydeApiGatewayRidesResource
#        RestApiId:
#          Ref: WildRydesApiGatewayRestApi
#        Integration:
#          Type: AWS_PROXY
#          IntegrationHttpMethod: POST
#          Uri:
#            Fn::Join:
#              - ':'
#              - - 'arn:aws:apigateway'
#                - Ref: 'AWS::Region'
#                - 'lambda'
#                - Fn::Join:
#                    - '/'
#                    - - 'path'
#                      - '2015-03-31'
#                      - 'functions'
#                      - Fn::GetAtt: [RequestUnicornLambdaFunction, Arn]
#                      - 'invocations'
#    WildRydesApiGatewayDeployment:
#      Type: AWS::ApiGateway::Deployment
#      Properties:
#        Description: Wild Rydes Api
#        RestApiId:
#          Ref: WildRydesApiGatewayRestApi
#        StageName: ${opt:stage, 'dev'}




  Outputs:

##### part 1, view url using sls info -v
#    WildRydesApiGatewayUrl:
#      Description: 'Wild Rydes Api Gateway URL'
#      Value:
#        'Fn::Join':
#          - ''
#          - - 'https://'
#            - Ref: 'WildRydesApiGatewayRestApi'
#            - '.execute-api.'
#            - Ref: 'AWS::Region'
#            - '.amazonaws.com'
#            - "/${opt:stage, 'dev'}"

    WildRydesCognitoUserPoolId:
      Description: 'Wild Rydes Cognito User Pool ID'
      Value:
        Ref: 'WildRydesCognitoUserPool'
    WildRydesCognitoUserPoolClientId:
      Description: 'Wild Rydes Cognito User Pool Client ID'
      Value:
        Ref: 'WildRydesCognitoUserPoolClient'

    WildRydesDynamoDbARN:
      Description: 'Wild Rydes DynamoDB ARN'
      Value:
        'Fn::GetAtt': [WildRydesDynamoDBTable, Arn]
